In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.4.1


In [3]:
import numpy as np


In [4]:
X=np.arange(-3,9,2)

In [5]:
X

array([-3, -1,  1,  3,  5,  7])

In [6]:
y=np.arange(7,18,2)
y

array([ 7,  9, 11, 13, 15, 17])

In [7]:
X=tf.constant(X)
y= tf.constant(y)
X,y

(<tf.Tensor: shape=(6,), dtype=int64, numpy=array([-3, -1,  1,  3,  5,  7])>,
 <tf.Tensor: shape=(6,), dtype=int64, numpy=array([ 7,  9, 11, 13, 15, 17])>)

In [ ]:
tf.random.set_seed(42)
model=tf.keras.Sequential([
                           tf.keras.layers.Dense(1),
                           tf.keras.layers.Dense(100,activation='relu'),
                           tf.keras.layers.Dense(100,activation='relu'),
                           tf.keras.layers.Dense(1)
])
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              metrics=['mae'])
model.fit(X,y,epochs=1800)

In [ ]:
model.summary()

In [28]:
model.predict([18.7])

array([[30.921013]], dtype=float32)

In [ ]:
tf.random.set_seed(0)
model1= tf.keras.Sequential([
                            tf.keras.layers.Dense(1)
])
model1.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
              metrics=['mae'])
model1.fit(X,y,epochs=50,verbose=1)

In [40]:
tf.random.set_seed(20)
model2= tf.keras.Sequential([
                             tf.keras.layers.Dense(20,activation='relu'),
                             tf.keras.layers.Dense(30,activation='relu'),
                             tf.keras.layers.Dense(1)
])
model2.compile(loss='mae',
               optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
               metrics=['mae'])
model2.fit(X,y,epochs=200)

Epoch 1/200
1/1 [==============================] - 0s 330ms/step - loss: 12.7143 - mae: 12.7143
Epoch 2/200
1/1 [==============================] - 0s 6ms/step - loss: 12.7006 - mae: 12.7006
Epoch 3/200
1/1 [==============================] - 0s 8ms/step - loss: 12.6871 - mae: 12.6871
Epoch 4/200
1/1 [==============================] - 0s 8ms/step - loss: 12.6736 - mae: 12.6736
Epoch 5/200
1/1 [==============================] - 0s 5ms/step - loss: 12.6601 - mae: 12.6601
Epoch 6/200
1/1 [==============================] - 0s 4ms/step - loss: 12.6468 - mae: 12.6468
Epoch 7/200
1/1 [==============================] - 0s 4ms/step - loss: 12.6334 - mae: 12.6334
Epoch 8/200
1/1 [==============================] - 0s 9ms/step - loss: 12.6201 - mae: 12.6201
Epoch 9/200
1/1 [==============================] - 0s 5ms/step - loss: 12.6069 - mae: 12.6069
Epoch 10/200
1/1 [==============================] - 0s 6ms/step - loss: 12.5937 - mae: 12.5937
Epoch 11/200
1/1 [==============================] - 0s 9m